### ISSUE TITLE
include demo image?

### ISSUE THREAD

**Issue by shapr** [bergey/ghc-passes-graph#2]
What does this look like when it has demo data?

**Comment by bergey** [comment]
So far I've only run it on work data, and I probably shouldn't put that here.  One of us should run it on something public, like `lens` or `servant` and post the results.  At least a screenshot; ideally the live JS / D3 one also.  I want to add some interactive mouseover / filter at some point; I suppose until then the screenshot is just as good.

**Comment by bergey** [comment]
I'm closing this, based on the commit that I just pushed.  Please do open another issue if you have any more ideas about improving docs or other aspects.
